# Drupal with PostgreSQL
#
# Access over "http://localhost"
#
# During initial Drupal setup,
# Database type: PostgreSQL
# Database name: drupal
# Database username: drupal
# Database password: mypass or the password defined in docker secrets
# ADVANCED OPTIONS
# - HOST: drupaldb
# - PORT: 5432 
# even if you are fowarding to a different 
# port this is the exposed port inside containers network

version: '3.7'

services:
  drupal:
    image: drupal:latest
    ports:
      - 80:80
    depends_on:
      - drupaldb
    secrets:
      - psql.drupal.passwd
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: /run/secrets/psql.drupal.passwd
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    networks: 
      - backend
  drupaldb:
    image: postgres:latest
    ports:
      - 5433:5432
    secrets:
      - psql.root.passwd
      - psql.drupal.passwd
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/psql.root.passwd
      #Variables used inside init-db scripts to not use root user of db.
      #Observe that secrets is beeing in use for it
      DRUPAL_DB: drupal
      DRUPAL_USER: drupal
      DRUPAL_PASSWORD_FILE: /run/secrets/psql.drupal.passwd
    volumes:
      - drupal-db:/var/lib/postgresql/data
      - ./drupal-init.sh:/docker-entrypoint-initdb.d/drupal-init-secret.sh
    networks: 
        - backend
networks: 
  backend:
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  drupal-db:
secrets:
  psql.root.passwd:
    file: ./psql.root.passwd
  psql.drupal.passwd:
    file: ./psql.drupal.passwd