#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE $DRUPAL_USER WITH LOGIN NOINHERIT ENCRYPTED PASSWORD '$DRUPAL_PASSWORD';
    CREATE DATABASE $DRUPAL_DB;
    GRANT ALL PRIVILEGES ON DATABASE $DRUPAL_DB TO $DRUPAL_USER;
    ALTER DATABASE $DRUPAL_DB SET bytea_output = 'escape';
EOSQL