apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod5
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: /var/www/html
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim