apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: drupal-db-claim
    namespace: drupal
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
        