apiVersion: v1
kind: Service
metadata:
  labels:
    app: drupal
  name: drupal
  namespace: drupal
spec:
  type: NodePort
  ports:
    - name: "drupal-service"
      port: 5000
      targetPort: 80
      nodePort: 30000
  selector:
    app: drupal
